app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// route to login
Route::post('user/login',array('as' => 'user.login', 'uses' => 'UserController@login'));

//route to logiut
Route::get('user/logout',array('as' => 'user.logout', 'uses' => 'UserController@logout'));

// route to show the newsfeed of a particular user
Route::get('user/{id}/newsFeed',array('as' => 'user.newsFeed', 'uses' => 'UserController@newsFeed'));

//route to search all the existing users 
Route::get('user/search',array('as' => 'user.search', 'uses' => 'UserController@search'));

//route to show the profile page of a friend
Route::get('friend/{id}/profile',array('as' => 'friend.profile', 'uses' => 'FriendController@profile'));

//route to show the newsFeed of a friend
Route::get('friend/{id}/newsFeed',array('as' => 'friend.newsFeed', 'uses' => 'FriendController@newsFeed'));

//route to create a new post
Route::get('post/{id}/addNew',array('as' => 'post.addNew', 'uses' => 'PostController@addNew'));

//route to create a new comment
Route::get('comment/{id}/{id2}/addNew',array('as' => 'comment.addNew', 'uses' => 'CommentController@addNew'));

//route to check friendship between two users
Route::get('friend/{id}/{id2}/profile',array('as' => 'friend.checkFriendship', 'uses' => 'FriendController@checkFriendship'));

//route to add friend
Route::get('friend/{id}/{id2}/addFriend',array('as' => 'friend.addFriend', 'uses' => 'FriendController@addFriend'));

//route to un-friend a friend
Route::get('friend/{id}/{id2}/unFriend',array('as' => 'friend.unFriend', 'uses' => 'FriendController@unFriend'));


//create Controller for users table
Route::resource('user','UserController');

//create Controller for friends table
Route::resource('friend','FriendController');

//create Controller for posts table
Route::resource('post','PostController');

//create controller for comments table
Route::resource('comment','CommentController');

//Home page
Route::get('/',array('as' => 'home', 'uses' => 'PostController@index'));
// Route::get('/', function()
// {
// 	return View::make('hello');
// });

app/models/Comment.php
<?php

class Comment extends Eloquent {
    
    	public static $rules = array(
        'message' => 'required'
     
        );
   
}

app/controllers/CommentController.php
<?php

class CommentController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		//
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{   
		$post = Post::find($id);
	    $comments = Post::find($id)->comments()->paginate(6);
	    return View::make('comment.showComments', compact('comments','post'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		 $comment = Comment::find($id);
		 $post_id = $comment->post_id;
		 $comment->delete();
		 return Redirect::action('CommentController@show',$post_id);
	}
	
	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function addNew($id,$user_id)
	{
		$input = Input::all();
		$name = User::find($user_id);
		print_r($name->fullname);
		$v = Validator :: make($input, Comment::$rules);
		if($v -> passes()){
		
		    $comment = new Comment(); 
			$comment->message = $input['message'];
			$comment->author = $name->fullname;
			$comment->user_id = $user_id;
			Post::find($id)->comments()->save($comment);
			return Redirect::action('CommentController@show',$id);
		
		}else{
		 	return Redirect::action('CommentController@show',$id)->withErrors($v);
			
		 }
	}

}

app/views/comment/showComments.blade.php
@extends ('master')

@section('title')
    Comments Page
@stop

@section('content')
   
    <div class='row'>
            <div class="first-heading">
              <!--<h2 id="main-heading"></h2>-->
            </div>
           
               
            @if (Auth::check())
                <!--<h3 class='well'>{{ Auth::user() -> fullname}}'s News Feed</h3>-->
                <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                                <div class="navbar-header">
                                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                  </button>
                                  <span class="visible-xs navbar-brand">Sidebar menu</span>
                                </div>
                                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                                  <ul class="nav navbar-nav">
                                    <!--<li class="active">{{ Auth::user() -> fullname }} {{ link_to_route('user.logout',"Sign Out") }}</li>-->
                                    <li>{{ link_to_route('user.newsFeed',"My News Feed",array(Auth::user() -> id ) ) }}</li>
                                    <li>{{ link_to_route('friend.show',"My Friends List",array(Auth::user() -> id ) ) }}</li>
                                    <li>{{ link_to_route('post.addNew',"Add a new Post",array(Auth::user() -> id ) ) }}</li>
                                    <!--<li><a href="#">Reviews <span class="badge">1,118</span></a></li>-->
                                  </ul>
                                </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
                    
                        <!--<h3 class='well'>{{ Auth::user() -> fullname}}'s News Feed</h3>-->
                        <!--<h3 class='well'> Posts</h3>-->
                <div class='col-sm-6'>
                @if($post)
                    <div class="panel">
                            <div class="panel-heading">
                                {{{ $post->author}}}
                                <div class ="text-center"> 
                                Title: {{ $post->title }}
                                
                                      <div class="dropdown">
                                          <button type="button" data-toggle="dropdown"><span class="caret"></span></button>
                                          <ul class="dropdown-menu">
                                               {{--<li>{{{ link_to_route('post.show',array($post->id)) }}} Delete </li> --}}
                                              {{-- <li>{{{ link_to_route('post.edit', $post->id,array($post->id)) }}} </li> --}}
                                    
                                          </ul>
                                        </div>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class=post-body>
                                     {{{ $post->message}}} 
                                </div>
                                   
                            </div>
                            <div class="panel-footer">
                                 <ul class="list-inline">
                                     <li>{{ link_to_route('comment.show',"Comments",array($post->id)) }} </li>
                    
                                  </ul>
                            </div>
                            
                        </div> 
                        
                    <div class = "addPost">
                 
                    <!--￼{{ Form::open(array('url' => secure_url('user/addNew'),'class'=>'form')) }}-->
                    {{ Form :: open(array('method' => 'GET' , 'route' => array('comment.addNew',$post -> id,Auth::user() -> id))) }}
                       <p></p>
                    {{ Form::label('message', 'Message: ') }} 
                    {{ Form::text('message',null,['class' => "form-control " ]) }}
                     {{ $errors->first('message') }}
                    <p></p>
    
                    {{Form::submit('Create', ['class' => 'btn btn-large btn-primary openbutton'])}}
                    {{ Form::close() }}
                     </div>
                    <p></p>
                    <p></p>
                        @if($comments) 
                        @foreach($comments as $comment)
                          
                            <div class="panel">
                                   <div class="panel-heading">
                                       
                                        <div class ="text-center"> {{{ $comment->author }}}
                                         @if($comment->user_id == Auth::user()->id) 
                                             <div class = "delete">
                                               {{ Form :: open(array('method' => 'DELETE' , 'route' => array('comment.destroy',$comment->id))) }}
                                               {{ Form :: submit('Delete')  }}
                                               {{Form :: close() }}
                                             </div>
                                        @endif
                                        </div>
                                    </div>
                                    <div class="panel-body">
                                    <div class=post-body>
                                       {{{ $comment->message}}}
                                     </div>
                                    </div>
                                    <div class="panel-footer"> 
                                        
                                    </div>
                            </div>
                        @endforeach
                        @endif 
                          {{$comments->links()}}
                @endif
                   
            </div> 
            <div class="col-sm-3">
                    {{ Auth::user() -> fullname}} {{ link_to_route('user.logout',"Sign Out") }}
                </div>
            @endif    
      </div>
  
@stop