app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// route to login
Route::post('user/login',array('as' => 'user.login', 'uses' => 'UserController@login'));

//route to logiut
Route::get('user/logout',array('as' => 'user.logout', 'uses' => 'UserController@logout'));

// route to show the newsfeed of a particular user
Route::get('user/{id}/newsFeed',array('as' => 'user.newsFeed', 'uses' => 'UserController@newsFeed'));

//route to search all the existing users 
Route::get('user/search',array('as' => 'user.search', 'uses' => 'UserController@search'));

//route to show the profile page of a friend
Route::get('friend/{id}/profile',array('as' => 'friend.profile', 'uses' => 'FriendController@profile'));

//route to show the newsFeed of a friend
Route::get('friend/{id}/newsFeed',array('as' => 'friend.newsFeed', 'uses' => 'FriendController@newsFeed'));

//route to create a new post
Route::get('post/{id}/addNew',array('as' => 'post.addNew', 'uses' => 'PostController@addNew'));

//route to create a new comment
Route::get('comment/{id}/{id2}/addNew',array('as' => 'comment.addNew', 'uses' => 'CommentController@addNew'));

//route to check friendship between two users
Route::get('friend/{id}/{id2}/profile',array('as' => 'friend.checkFriendship', 'uses' => 'FriendController@checkFriendship'));

//route to add friend
Route::get('friend/{id}/{id2}/addFriend',array('as' => 'friend.addFriend', 'uses' => 'FriendController@addFriend'));

//route to un-friend a friend
Route::get('friend/{id}/{id2}/unFriend',array('as' => 'friend.unFriend', 'uses' => 'FriendController@unFriend'));


//create Controller for users table
Route::resource('user','UserController');

//create Controller for friends table
Route::resource('friend','FriendController');

//create Controller for posts table
Route::resource('post','PostController');

//create controller for comments table
Route::resource('comment','CommentController');

//Home page
Route::get('/',array('as' => 'home', 'uses' => 'PostController@index'));
// Route::get('/', function()
// {
// 	return View::make('hello');
// });

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;
use Codesleeve\Stapler\ORM\StaplerableInterface;
use Codesleeve\Stapler\ORM\EloquentTrait;

class User extends Eloquent implements UserInterface, RemindableInterface, StaplerableInterface {

	// use UserTrait, RemindableTrait;
	use EloquentTrait, UserTrait, RemindableTrait;


	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';
	public function __construct(array $attributes = array()) {
			$this->hasAttachedFile('image', [
			'styles' => [
			'medium' => '300x300',
			'thumb' => '100x100'
			]
	]);
			parent::__construct($attributes);
	}
	
	public static $rules = array(
        'username' => 'required|email|unique:users',
        'password' => 'required|min:4',
        'year'     => 'required|min:4',
        'month'    => 'required',
        'day'      => 'required',
         'fullname'    => 'required',
        );

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array('password', 'remember_token');
	function posts()
	{
		return $this->hasMany('Post');
	}
		function comments()
	{
		return $this->hasMany('Comment');
	}
		function friends()
	{
		return $this->belongsToMany('User','friends','user_id','friend_id');
	}
	
	function getDates()
	{
		return array('created_at',
		'updated_at', 'birth_at');
	}
}

app/controllers/UserController.php
<?php

class UserController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		return View::make('user.report');	
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{  
		$posts = Post::whereRaw('privacy = "public" ')->get();
        return View::make('user.create_user', compact('posts'));
	  
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
	
		$input = Input::all();
		$v = Validator :: make($input, User::$rules);
		if($v -> passes()){
			$password = $input['password'];
			$encrypted = Hash::make($password);
		    $user = new User(); 
			$user->username = $input['username']; 
			$user->password = $encrypted; 
			$y=($input['year']);
		    $m=($input['month']);
		    $d=($input['day']);
		    $dob = "$y"."-$m-"."$d";
			$user->dob = $dob; 
			$user->fullname = $input['fullname'];
			$user->image = $input['image'];
			$user->save();
			return Redirect::action('PostController@index');
		
		}else{
		 	return Redirect::action('UserController@create')->withErrors($v);
			
		 }
	}


	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	   $user = User::find($id);
	   $posts = Post::whereRaw('privacy = "public" ')->get();
       $d = Carbon\Carbon::createFromFormat('Y-m-d', $user->dob)->toDateString();
       $age = Carbon\Carbon::createFromFormat('Y-m-d', $user->dob)->age;
       return View::make('user.profile_not_logged_in', compact('user','age','posts'));
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}


	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}
	public function login()
	{
	
		$userdata = array(
			'username' => Input::get('username'),
			'password' => Input::get('password')
			);
	   
		if (Auth::attempt($userdata))
		{
			$val = $userdata["username"];
			$user = User::whereRaw('username = ? ', array($val))->get();
			//$user = User::where(' username' , '=', $val)->get();
			$id = $user[0]->id;
			$posts = User::find($user[0]->id)->posts;
		    return Redirect::action('UserController@newsFeed',$id);
		}else{
			// Session::put('login_error','Invalid username or password');
			Session::flash('login_error','Invalid username or password');
			// $value = Session::get('login_error');
			return Redirect::to(URL::previous())->withInput();
		}
		
	}

	
	public function logout(){
		Auth::logout();
		return Redirect::action('PostController@index');
	}
	
	// shows the newsfeed of a user with authorised posts
	public function newsFeed($id){
		

		 $sql= "  select * from posts p ,users u,friends f  where u.id = f.user_id AND  u.id=? And f.friend_id=p.user_id ANd 
					 p.privacy = 'friends'";
        $postsFriends = DB::select($sql, array($id));
         //print_r($posts[0]->title);
		$ownPosts = User::find($id)->posts()->whereRaw('privacy != "public"')->orderBy('id', 'DESC')->get();
		$publicPosts = Post::whereRaw('privacy = "public" ')->orderBy('id', 'DESC')->get();
		$posts = $ownPosts->merge($publicPosts);
		// $posts = $posts1->merge($postsFriends);
        return View::make('user.newsFeed', compact('posts','postsFriends'));
	}
	
	//searh a user
	public function search(){
		// $input = Input::get('username');
	    $input = Input::all();
	    $val = $input['username'];
		$users = User::whereRaw('fullname like ? ', array("%$val%"))->get();
		return View::make('user.showUsers', compact('users'));
	}
}

app/views/user/create_user.blade.php
@extends ('master')

@section('title')
    Sign Up
@stop

@section('content')
   
    <div class='row'>
            <div class="first-heading">
              <h2 id="main-heading">New User Page</h2>
            </div>
            
         <div class='col-sm-12'>        
            @if (Auth::check())
                    {{ Auth::user() -> username }} {{ link_to_route('user.logout',"Sign Out") }} 
                    <h3>You are already signed in</h3>
            @else
                <!--<div class="form-group">-->
            
                <div >
                    
                    {{ Form::open(array('route' => 'user.store', 'files' => true)) }}
                    {{ Form::label('username', 'UserName: ') }}
                    {{ Form::text('username',null,['class' => "form-control", 'placeholder'=>'xyz@a.org']) }}
                     <!--{{ $errors->first('UserName', '<p class="help-block">:message</p>') }}-->
                    {{ $errors->first('username') }}
                    <p></p>
                    {{ Form::label('fullname', 'FullName:') }}
                    {{ Form::text('fullname',null,['class' => "form-control",'placeholder'=>'enetr your name']) }}
                    {{ $errors->first('fullname') }}
                    <p></p>
                    {{ Form::label('password', 'Password: ') }} 
                    {{ Form::password('password',['class' => "form-control"]) }}
                    <!--{{ $errors->first('password', '<p class="help-block">:message</p>') }}-->
                    {{ $errors->first('password') }}
                       <p></p>
                    <!--{{Session::get('login_error')}}-->
                    {{ Form::label('dateOfBirth', 'Date of Birth:') }}
                    <p></p>
                    {{ Form::text('year',null,['placeholder'=>'year']) }}
                    {{ $errors->first('year') }}
                    {{ Form::text('month',null,['placeholder'=>'month']) }}
                    {{ $errors->first('month') }}
                    {{ Form::text('day',null,['placeholder'=>'day']) }}
                    {{ $errors->first('day') }}
                    <p></p>
                    {{ Form::label('image', 'Image:') }}
                    {{ Form::file('image') }}
                     <p></p>
                    {{Form::submit('Sign UP', ['class' => 'btn btn-large btn-primary openbutton'])}}
                    {{ Form::close() }}
               
               </div>   
            @endif
               </div> 
      
      </div>
  
@stop   
                
          
  

app/views/user/newsFeed.blade.php
@extends ('master')

@section('title')
    User's News Feed
@stop

@section('content')
   
    <div class='row'>
            <div class="first-heading">
              <!--<h2 id="main-heading"></h2>-->
            </div>
           
               
            @if (Auth::check())
                <h3 class='well'>{{ Auth::user() -> fullname}}'s News Feed
                </h3>
                <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                                <div class="navbar-header">
                                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                  </button>
                                  <span class="visible-xs navbar-brand">Sidebar menu</span>
                                </div>
                                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                                  <ul class="nav navbar-nav">
                                    <!--<li class="active">{{ Auth::user() -> fullname }} {{ link_to_route('user.logout',"Sign Out") }}</li>-->
                                    <li>{{ link_to_route('user.newsFeed',"My News Feed",array(Auth::user() -> id ) ) }}</li>
                                    <li>{{ link_to_route('friend.show',"My Friends List",array(Auth::user() -> id ) ) }}</li>
                                    <li>{{ link_to_route('friend.checkFriendship',"My Profile Page",array(Auth::user() -> id,Auth::user() -> id))}}</li>
                                  </ul>
                                </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
                    
                        <!--<h3 class='well'>{{ Auth::user() -> fullname}}'s News Feed</h3>-->
                        <!--<h3 class='well'> Posts</h3>-->
                 <div class='col-sm-6'>
                    <div class = "addPost">
                 
                    <!--￼{{ Form::open(array('url' => secure_url('user/addNew'),'class'=>'form')) }}-->
                    {{ Form :: open(array('method' => 'GET' , 'route' => array('post.addNew',Auth::user() -> id))) }}
                    {{ Form::label('title', 'title: ') }}
                    {{ Form::text('title',null,['class' => "form-control"]) }}
                     {{ $errors->first('title') }}
                       <p></p>
                    {{ Form::label('message', 'Message: ') }} 
                    {{ Form::text('message',null,['class' => "form-control " ]) }}
                    {{ $errors->first('message') }}
                    <p></p>
                    {{Form::label('privacy', 'Public')}}
                    {{ Form::radio('privacy', 'public',true) }}
                    {{Form::label('privacy', 'Friends')}}
                    {{ Form::radio('privacy', 'friends') }}
                    {{Form::label('privacy', 'private')}}
                    {{ Form::radio('privacy', 'private') }}
                    <p></p>
                    {{Form::submit('Create', ['class' => 'btn btn-large btn-primary openbutton'])}}
                    {{ Form::close() }}
                     </div>
                    <p></p>
                    <p></p>
                    <p></p>
                    @if($posts) 
                    @foreach($posts as $post)
                       <div class="panel">
                            <div class="panel-heading">
                                {{{ $post->author}}}
                                <div class ="text-center"> Title: {{{ $post->title }}}
                                    @if($post->user_id == Auth::user()->id) 
                                      <div class="dropdown">
                                          <button type="button" data-toggle="dropdown"><span class="caret"></span></button>
                                          <ul class="dropdown-menu">
                                             
                                              <li>{{ link_to_route('post.edit','Edit',array($post->id)) }}</li>
                                              
                                            
                                          </ul>
                                        </div>
                                    @endif
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class=post-body>

                                  Message: {{{ $post->message}}}
                                 </div>
                                  
                            </div>
                            <div class="panel-footer">
                                 <ul class="list-inline">
                                     <li>{{ link_to_route('comment.show',"Comments",array($post->id)) }} </li>
                                        @if($post->user_id == Auth::user()->id)    
                                            <div class = "delete">
                                               {{ Form :: open(array('method' => 'DELETE' , 'route' => array('post.destroy',$post->id))) }}
                                               {{ Form :: submit('Delete',array('class' => 'btn btn-danger'))  }}
                                               {{Form :: close() }}
                                             </div>
                                         @endif
                                  </ul>
                                 
                            </div>
                        </div>
                    @endforeach
                    @endif 
                     @if($posts) 
                    @foreach($postsFriends as $post)
                       <div class="panel">
                            <div class="panel-heading">
                                {{{ $post->author}}}
                                <div class ="text-center"> Title: {{{ $post->title }}}
                                    <!--@if($post->user_id == Auth::user()->id) -->
                                    <!--  <div class="dropdown">-->
                                    <!--      <button type="button" data-toggle="dropdown"><span class="caret"></span></button>-->
                                    <!--      <ul class="dropdown-menu">-->
                                             
                                    <!--          <li>{{ link_to_route('post.edit','Edit',array($post->id)) }}</li>-->
                                              
                                            
                                    <!--      </ul>-->
                                    <!--    </div>-->
                                    <!--@endif-->
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class=post-body>

                                  Message: {{{ $post->message}}}
                                 </div>
                                  
                            </div>
                            <div class="panel-footer">
                                 <ul class="list-inline">
                                     <li>{{ link_to_route('comment.show',"Comments",array($post->id)) }} </li>
                                        <!--@if($post->user_id == Auth::user()->id)    -->
                                        <!--    <div class = "delete">-->
                                        <!--       {{ Form :: open(array('method' => 'DELETE' , 'route' => array('post.destroy',$post->id))) }}-->
                                        <!--       {{ Form :: submit('Delete',array('class' => 'btn btn-danger'))  }}-->
                                        <!--       {{Form :: close() }}-->
                                        <!--     </div>-->
                                        <!-- @endif-->
                                  </ul>
                                 
                            </div>
                        </div>
                    @endforeach
                    @endif 
                   
                </div> 
                <div class="col-sm-3">
                    {{ Auth::user() -> fullname}} {{ link_to_route('user.logout',"Sign Out") }}
                </div>
            @endif    
      </div>
  
@stop

app/views/user/profile_not_logged_in.blade.php
@extends ('master')

@section('title')
    Profile
@stop

@section('content')
   
    <div class='row'>
        <h3 class='well'>{{$user->fullname}}'s Profile</h3>
         <div class='col-sm-3'>
              <img class="img-circle" src ="{{ asset($user->image->url('thumb'))}}" alt='photo'>
              <div class = "profile"> 
                   Name: {{{$user->fullname}}} 
               <div></div>
                   age :{{{$age}}}
                  
              </div>      
        </div> 
    
    <div class='col-sm-9'>
        <h3 class='well'>Public Posts</h3>
                 @if($posts) 
                    @foreach($posts as $post)
                       <div class="panel">
                            <div class="panel-heading">
                                
                                {{{ $post->author}}} 
                                <div class ="text-center"> Title: {{{ $post->title}}}
                                     
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class=post-body>

                                  Message: {{{ $post->message}}}
                                 </div>
                                  
                            </div>
                            <div class="panel-footer">
                                 <ul class="list-inline">
                                     <li>{{ link_to_route('comment.show',"Comments",array($post->id)) }} </li>
                                  </ul>
                            </div>
                        </div>
                    @endforeach
                @endif  
        </div>
     </div> 
  @stop                
                   
                    
                   
                
                
          
            
      
  

app/views/user/report.blade.php
@extends('master')

@section('title')
Documentation
@stop

@section('content')
    <h2 id="main-heading">Comments about Assignment</h2>
    <ol>
      <li>Apparently all required functionalities are fullfilled .</li>
      <li>Looks of web site could have been improved alot. Structure of Home page 
          in terms of positioning of posts and comments could have been made look better.
      </li>
      <li>Extra features like exact date and time of comments and like or dislike 
          buttons could have been also included .
      </li>
    </ol>
@stop

app/views/user/showUsers.blade.php
@extends ('master')

@section('title')
    showUsers
@stop

@section('content')
   
    <div class='row'>
           
            <div class="first-heading">
              <h2 id="main-heading">User Search Result</h2>
            </div>
            <!--<div class='col-sm-12'>-->
        @if (Auth::check())
            <div class = "  newsfeed">
                {{ Auth::user() -> fullname }} {{ link_to_route('user.logout',"Sign Out") }}
            </div>
            <div class="col-sm-3">
                    <div class="sidebar-nav">
                        <div class="navbar navbar-default" role="navigation">
                                <div class="navbar-header">
                                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                  </button>
                                  <span class="visible-xs navbar-brand">Sidebar menu</span>
                                </div>
                                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                                  <ul class="nav navbar-nav">
                                    <!--<li class="active">{{ Auth::user() -> fullname }} {{ link_to_route('user.logout',"Sign Out") }}</li>-->
                                    <li>{{ link_to_route('user.newsFeed',"My News Feed",array(Auth::user() -> id ) ) }}</li>
                                    <li>{{ link_to_route('friend.show',"My Friends List",array(Auth::user() -> id ) ) }}</li>
                                    <!--<li><a href="#">Reviews <span class="badge">1,118</span></a></li>-->
                                  </ul>
                                </div><!--/.nav-collapse -->
                        </div>
                    </div>
                </div>
                <p></p>
                <p></p>
            <div class='col-sm-9'>
                      @if($users) 
                        @foreach($users as $user)
                       <div class="name">
                        <img class="img-circle" src ="{{ asset($user->image->url('thumb'))}}" alt='photo'>
                        {{ link_to_route('friend.checkFriendship', $user->fullname,array($user->id,Auth::user() -> id))}}
                       </div>
                        @endforeach
                    @endif 
         @else
                    @if($users) 
                        @foreach($users as $user)
                        <div class="name">
                        <img class="img-circle" src ="{{ asset($user->image->url('thumb'))}}" alt='photo'>
                        {{ link_to_route('user.show', $user->fullname,array($user->id))}}
                        </div>
                        @endforeach
                    @endif  
                
        @endif 
                
            </div>  
      </div>
  
@stop