app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

// route to login
Route::post('user/login',array('as' => 'user.login', 'uses' => 'UserController@login'));

//route to logiut
Route::get('user/logout',array('as' => 'user.logout', 'uses' => 'UserController@logout'));

// route to show the newsfeed of a particular user
Route::get('user/{id}/newsFeed',array('as' => 'user.newsFeed', 'uses' => 'UserController@newsFeed'));

//route to search all the existing users 
Route::get('user/search',array('as' => 'user.search', 'uses' => 'UserController@search'));

//route to show the profile page of a friend
Route::get('friend/{id}/profile',array('as' => 'friend.profile', 'uses' => 'FriendController@profile'));

//route to show the newsFeed of a friend
Route::get('friend/{id}/newsFeed',array('as' => 'friend.newsFeed', 'uses' => 'FriendController@newsFeed'));

//route to create a new post
Route::get('post/{id}/addNew',array('as' => 'post.addNew', 'uses' => 'PostController@addNew'));

//route to create a new comment
Route::get('comment/{id}/{id2}/addNew',array('as' => 'comment.addNew', 'uses' => 'CommentController@addNew'));

//route to check friendship between two users
Route::get('friend/{id}/{id2}/profile',array('as' => 'friend.checkFriendship', 'uses' => 'FriendController@checkFriendship'));

//route to add friend
Route::get('friend/{id}/{id2}/addFriend',array('as' => 'friend.addFriend', 'uses' => 'FriendController@addFriend'));

//route to un-friend a friend
Route::get('friend/{id}/{id2}/unFriend',array('as' => 'friend.unFriend', 'uses' => 'FriendController@unFriend'));


//create Controller for users table
Route::resource('user','UserController');

//create Controller for friends table
Route::resource('friend','FriendController');

//create Controller for posts table
Route::resource('post','PostController');

//create controller for comments table
Route::resource('comment','CommentController');

//Home page
Route::get('/',array('as' => 'home', 'uses' => 'PostController@index'));
// Route::get('/', function()
// {
// 	return View::make('hello');
// });

app/views/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>@yield('title')</title>
    @section('java')
    @show
    <!-- Bootstrap core CSS -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
 
    <link href="css/style.css" type="text/css" rel="stylesheet">
    {{ HTML::style('css/style.css') }}
       <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  </head>
  <body>
     <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <!--<a class="navbar-brand" href="#">Chain</a>-->
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <!--<ul class="nav navbar-nav">-->
             <ul class="list-inline">
              <li>{{ link_to_route('post.index', 'HOME') }}</li>
              <li>{{ link_to_route('post.create', 'ERD Diagram') }}</li>
              <li>{{ link_to_route('user.index', 'Report') }}</li>
              <li> {{ link_to_route('user.create', 'sign up') }}</li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>
      @section('content')
      Default content
      @show 
    </div>
  </body>      
</html>